admin2675_index:
    path:     /
    defaults: { _controller: "OCUserBundle:User:index" }
    methods:  GET

admin2675_show:
    path:     /{id}/show
    defaults: { _controller: "OCUserBundle:User:show" }
    methods:  GET

admin2675_new:
    path:     /new
    defaults: { _controller: "OCUserBundle:User:new" }
    methods:  [GET, POST]

admin2675_edit:
    path:     /{id}/edit
    defaults: { _controller: "OCUserBundle:User:edit" }
    methods:  [GET, POST]

admin2675_delete:
    path:     /{id}/delete
    defaults: { _controller: "OCUserBundle:User:delete" }
    methods:  DELETE
